name: 'Check Hosts via SSH'
description: 'Checks if hosts are reachable via SSH'
inputs:
  hosts_file:
    description: 'Path to the hosts.cfg file'
    required: true

runs:
  using: node20
  main: dist/index.js
